[book]
authors = ["iamazy"]
language = "en"
multilingual = false
src = "src"
title = "Blog Translation"

[output.html]
additional-css = ["theme/ferris.css", "theme/2018-edition.css"]
additional-js = ["theme/ferris.js"]
git-repository-url = "https://github.com/fucking-translation/blog"

[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = true
level = 0